# Archivo de configuraci칩n para Netlify

# Regla de reescritura para los posts del blog.
# Esta es la pieza clave que permite que las URLs limpias funcionen.
[[redirects]]
  # Cuando un navegador o bot pida una URL como /blog/mi-primer-post...
  from = "/blog/*"

  # ...Netlify internamente le servir치 el archivo post.html sin cambiar la URL.
  to = "/post.html"

  # El status 200 significa que es una reescritura, no una redirecci칩n.
  # La URL en el navegador del usuario no cambiar치.
  status = 200
